### ISSUE TITLE
Methods to parse Years of Experience, Location, Sponsorships

### ISSUE THREAD

**Issue by riteshghorse** [ultraultimated/savitar#1]

**Comment by riteshghorse** [comment]
With $.get(URL), we can fetch the page and use $.find(regex) to search for patterns described in  #15

**Comment by kdave97** [comment]
Yes, I tried isomorphic-fetch and cheerio to parse the text and cleaning the description. We need to work on regex patterns to get years of experience and sponsorship availability.
