### ISSUE TITLE
ESLint pattern formatting in content.js

### ISSUE THREAD

**Issue by riteshghorse** [ultraultimated/savitar#32]
ESLint static code analysis shows some errors in "if statement formatting" and use of non camelcase variable names

**Comment by riteshghorse** [comment]
keeping the issue open if there are more changes to this file.

**Comment by devarshshah15** [comment]
Try to see how to conform files to eslint style checking standards.

**Comment by riteshghorse** [comment]
Yes. Looks like we have to do it manually in some files.
