### ISSUE TITLE
Could not load extension. error in manifest file.

### ISSUE THREAD

**Issue by riteshghorse** [ultraultimated/savitar#42]
I am getting this error when I tried to reload the extension. Anyone encountered this error before? or know what's wrong?
```
Could not load JavaScript 'dist/content.js' for content script.
Could not load manifest.
```

**Comment by binpatel31** [comment]
You have to build the project first using - `npm run-script build`. 
First run npm install and then use above command to build it.

**Comment by riteshghorse** [comment]
Thanks. It is working now.

**Comment by riteshghorse** [comment]
Can we do anything to resolve this warning?
```
This extension includes the key file '/home/ritesh/savitar/node_modules/public-encrypt/test/test_key.pem'. You probably don't want to do that.
```

**Comment by ultraultimated** [comment]
Is this error coming in your local machine or a warning? if so please tell us the steps to recreate the error. My guess is .pem includes certificates and keys and therefore it might give you warning that it shouldn't be a part of extension.

**Comment by riteshghorse** [comment]
I think it is a warning. So should we put it into some ignore file or something?

**Comment by ultraultimated** [comment]
It is already in ignore file. You can safely ignore the warning. Close the issue once you are satisfied.

**Comment by riteshghorse** [comment]
Makes sense.
