### ISSUE TITLE
Research and Learn about NER techniques

### ISSUE THREAD

**Issue by binpatel31** [ultraultimated/savitar#5]
- How to implement NER ?
- Integrate it with JavaScript.

**Comment by devarshshah15** [comment]
Trying Stanford NER to find location.

**Comment by kdave97** [comment]
Wink-ner seems to work only on the training data that you provide. Need to figure out a way it can use a pretrained model as well as use new data for training.

**Comment by kdave97** [comment]
Also, lookout for integrating customizable entities in stanford NER.

**Comment by devarshshah15** [comment]
Prepared custom training data.
